#!/usr/bin/env python3
"""
deploy.py — OmniBot Deployment Configurator
============================================
Writes deployment.env with the chosen deployment mode and IP addresses.
All launch scripts (launch_simulation.sh, launch_teleop.sh, etc.) source
deployment.env automatically, so changing mode here takes effect on the
next script run.

Usage
-----
    python deploy.py                              # interactive menu
    python deploy.py --mode single               # non-interactive, single PC
    python deploy.py --mode multi \\
        --vla-ip  192.168.1.100 \\
        --pi-ip   192.168.1.101 \\
        --sim-ip  192.168.1.102              # non-interactive, multi-PC
    python deploy.py --mode multi --no-ping-check  # skip reachability check
    python deploy.py --show                        # print current config

Deployment Modes
----------------
single  All ROS 2 nodes run on one machine (e.g. RTX 5090 workstation).
        ROS_STATIC_PEERS is left unset — DDS uses localhost by default.
        Run any launch script normally; VLA + simulation share GPU resources.

multi   Three-machine distributed setup:
          Pi   (192.168.1.101) — robot driver, Nav2, SLAM, ROSBridge
          PC1  (192.168.1.100) — VLA inference (vla_node, smolvla_node)
          PC2  (192.168.1.102) — Isaac Sim / Gazebo + bev_stitcher_node
        Each machine sources deployment.env and gets the correct DDS peers.
        Run the appropriate launch script on each machine:
          Pi:  ./launch_rosbridge.sh
          PC1: ros2 launch omnibot_vla vla_desktop.launch.py
          PC2: ./launch_sim_pc.sh
"""

from __future__ import annotations

import argparse
import subprocess
import sys
from pathlib import Path

DEPLOY_ENV = Path(__file__).parent / "deployment.env"
_BANNER = """\
╔══════════════════════════════════════════╗
║      OmniBot Deployment Configurator     ║
╚══════════════════════════════════════════╝"""

_DEFAULT_VLA_IP = "192.168.1.100"
_DEFAULT_PI_IP = "192.168.1.101"
_DEFAULT_SIM_IP = "192.168.1.102"
_DEFAULT_DOMAIN = "30"


# ── Helpers ──────────────────────────────────────────────────────────────────


def _prompt(label: str, default: str) -> str:
    try:
        val = input(f"  {label} [{default}]: ").strip()
        return val if val else default
    except (EOFError, KeyboardInterrupt):
        print()
        sys.exit(0)


def _ping(ip: str) -> bool:
    result = subprocess.run(
        ["ping", "-c", "1", "-W", "1", ip],
        stdout=subprocess.DEVNULL,
        stderr=subprocess.DEVNULL,
    )
    return result.returncode == 0


def _check_reachability(ips: dict[str, str]) -> bool:
    print("\n  Checking reachability...")
    all_ok = True
    for label, ip in ips.items():
        ok = _ping(ip)
        mark = "✓" if ok else "✗"
        print(f"    {mark} {label:12s} {ip}")
        if not ok:
            all_ok = False
    return all_ok


def _write_env(mode: str, vla_ip: str, pi_ip: str, sim_ip: str, domain: str) -> None:
    if mode == "single":
        content = f"""\
# OmniBot deployment configuration — generated by deploy.py
# Run 'python deploy.py' to change mode.
DEPLOY_MODE=single
VLA_PC_IP=127.0.0.1
PI_IP=127.0.0.1
SIM_PC_IP=127.0.0.1
ROS_DOMAIN_ID={domain}
# Backward-compat alias kept for any scripts that still reference WORKSTATION_IP
WORKSTATION_IP=127.0.0.1
"""
    else:
        content = f"""\
# OmniBot deployment configuration — generated by deploy.py
# Run 'python deploy.py' to change mode.
DEPLOY_MODE=multi
VLA_PC_IP={vla_ip}
PI_IP={pi_ip}
SIM_PC_IP={sim_ip}
ROS_DOMAIN_ID={domain}
# Backward-compat alias kept for any scripts that still reference WORKSTATION_IP
WORKSTATION_IP={vla_ip}
"""
    DEPLOY_ENV.write_text(content)
    print(f"\n  ✓ Written to {DEPLOY_ENV}")


def _show_launch_hints(mode: str) -> None:
    if mode == "single":
        print("""
  Launch commands (all on this machine):
    Simulation:           ./launch_simulation.sh
    Teleop:               ./launch_teleop.sh
    Mobile manipulation:  ./launch_mobile_manipulation.sh
    Isaac Sim companion:  ros2 launch omnibot_bringup isaac_sim.launch.py
""")
    else:
        print("""
  Launch commands per machine:
    Pi  (robot driver):   ./launch_rosbridge.sh
    PC1 (VLA inference):  ros2 launch omnibot_vla vla_desktop.launch.py
    PC2 (simulation):     ./launch_sim_pc.sh

  Copy deployment.env to each machine so they all share the same peer config.
""")


def _show_current() -> None:
    if not DEPLOY_ENV.exists():
        print("  No deployment.env found. Run 'python deploy.py' to create one.")
        return
    print(f"  Current config ({DEPLOY_ENV}):")
    print()
    for line in DEPLOY_ENV.read_text().splitlines():
        if line and not line.startswith("#"):
            print(f"    {line}")
    print()


# ── Interactive flow ──────────────────────────────────────────────────────────


def _interactive_single(domain: str) -> tuple[str, str, str, str, str]:
    domain = _prompt("ROS Domain ID", domain)
    return "single", "127.0.0.1", "127.0.0.1", "127.0.0.1", domain


def _interactive_multi(domain: str, ping_check: bool) -> tuple[str, str, str, str, str]:
    print()
    vla_ip = _prompt("VLA PC IP   (vla_node, smolvla_node)", _DEFAULT_VLA_IP)
    pi_ip = _prompt("Pi IP       (robot driver, Nav2)     ", _DEFAULT_PI_IP)
    sim_ip = _prompt("Sim PC IP   (Isaac Sim / Gazebo)     ", _DEFAULT_SIM_IP)
    domain = _prompt("ROS Domain ID                        ", domain)

    if ping_check:
        ok = _check_reachability({"VLA PC": vla_ip, "Pi": pi_ip, "Sim PC": sim_ip})
        if not ok:
            print(
                "\n  [WARN] Some machines unreachable — deployment.env written anyway."
            )
            print(
                "         Ensure all machines are on the same LAN with ROS_DOMAIN_ID matching."
            )

    return "multi", vla_ip, pi_ip, sim_ip, domain


def _run_interactive(ping_check: bool) -> None:
    print(_BANNER)
    print("""
  Select deployment mode:
    1) Single workstation  — all nodes on one PC (RTX 5090 etc.)
    2) Multi workstation   — Pi + VLA PC + Sim PC (distributed)
""")
    try:
        choice = input("  Choice [1/2]: ").strip()
    except (EOFError, KeyboardInterrupt):
        print()
        sys.exit(0)

    current_domain = _DEFAULT_DOMAIN
    if DEPLOY_ENV.exists():
        for line in DEPLOY_ENV.read_text().splitlines():
            if line.startswith("ROS_DOMAIN_ID="):
                current_domain = line.split("=", 1)[1].strip()

    if choice == "1":
        print("\n  [single mode]")
        args_tuple = _interactive_single(current_domain)
    elif choice == "2":
        print("\n  [multi mode]")
        args_tuple = _interactive_multi(current_domain, ping_check)
    else:
        print("  Invalid choice. Run again and enter 1 or 2.")
        sys.exit(1)

    mode, vla_ip, pi_ip, sim_ip, domain = args_tuple
    _write_env(mode, vla_ip, pi_ip, sim_ip, domain)
    _show_launch_hints(mode)


# ── CLI ──────────────────────────────────────────────────────────────────────


def _build_parser() -> argparse.ArgumentParser:
    p = argparse.ArgumentParser(
        description="OmniBot deployment mode configurator.",
        formatter_class=argparse.RawDescriptionHelpFormatter,
        epilog=__doc__,
    )
    p.add_argument(
        "--mode",
        choices=["single", "multi"],
        help="Deployment mode: 'single' (one PC) or 'multi' (Pi + VLA PC + Sim PC).",
    )
    p.add_argument(
        "--vla-ip",
        default=_DEFAULT_VLA_IP,
        metavar="IP",
        help=f"VLA PC IP (default: {_DEFAULT_VLA_IP}). Multi mode only.",
    )
    p.add_argument(
        "--pi-ip",
        default=_DEFAULT_PI_IP,
        metavar="IP",
        help=f"Raspberry Pi IP (default: {_DEFAULT_PI_IP}). Multi mode only.",
    )
    p.add_argument(
        "--sim-ip",
        default=_DEFAULT_SIM_IP,
        metavar="IP",
        help=f"Sim PC IP (default: {_DEFAULT_SIM_IP}). Multi mode only.",
    )
    p.add_argument(
        "--domain",
        default=_DEFAULT_DOMAIN,
        metavar="N",
        help=f"ROS_DOMAIN_ID (default: {_DEFAULT_DOMAIN}).",
    )
    p.add_argument(
        "--no-ping-check",
        action="store_true",
        help="Skip IP reachability check (useful for CI or offline setup).",
    )
    p.add_argument(
        "--show", action="store_true", help="Print current deployment.env and exit."
    )
    return p


def main() -> None:
    parser = _build_parser()
    args = parser.parse_args()

    if args.show:
        _show_current()
        return

    ping_check = not args.no_ping_check

    if args.mode is None:
        _run_interactive(ping_check)
        return

    # Non-interactive path
    print(_BANNER)
    print(f"\n  Mode: {args.mode}")

    if args.mode == "single":
        _write_env("single", "127.0.0.1", "127.0.0.1", "127.0.0.1", args.domain)
    else:
        if ping_check:
            ok = _check_reachability(
                {
                    "VLA PC": args.vla_ip,
                    "Pi": args.pi_ip,
                    "Sim PC": args.sim_ip,
                }
            )
            if not ok:
                print("\n  [WARN] Some machines unreachable — continuing anyway.")
        _write_env("multi", args.vla_ip, args.pi_ip, args.sim_ip, args.domain)

    _show_launch_hints(args.mode)


if __name__ == "__main__":
    main()
