/*
 * Mock standards and compliance data for OhhO Comply.
 */

import { useState, useMemo, useCallback } from "react";

export type RequirementStatus = "done" | "review" | "open";

export interface Requirement {
  id: string;
  clause: string;
  description: string;
  status: RequirementStatus;
  owner: string;
  evidence: boolean;
}

export interface Standard {
  id: string;
  title: string;
  description: string;
  requirements: Requirement[];
}

const INITIAL_STANDARDS: Standard[] = [
  {
    id: "eu-machinery",
    title: "EU Machinery Reg · CE",
    description: "Essential health and safety requirements relating to the design and construction of machinery.",
    requirements: [
      { id: "r1", clause: "1.1.2", description: "Principles of safety integration (hazard elimination).", status: "done", owner: "Sarah J.", evidence: true },
      { id: "r2", clause: "1.2.2", description: "Control devices must be clearly visible and identifiable.", status: "done", owner: "Alex K.", evidence: true },
      { id: "r3", clause: "1.2.4.3", description: "Emergency stop device must have priority over all other commands.", status: "done", owner: "Alex K.", evidence: true },
      { id: "r4", clause: "1.3.7", description: "Risks related to moving parts must be mitigated by guards.", status: "review", owner: "Elena M.", evidence: true },
      { id: "r5", clause: "1.7.1", description: "Information and warnings on the machinery.", status: "open", owner: "Sarah J.", evidence: false },
    ],
  },
  {
    id: "iso-10218",
    title: "ISO 10218-1",
    description: "Safety requirements for industrial robots.",
    requirements: [
      { id: "r6", clause: "5.4.2", description: "Performance requirement for safety-related control systems.", status: "done", owner: "David L.", evidence: true },
      { id: "r7", clause: "5.5.3", description: "Reduced speed control (max 250 mm/s) in manual mode.", status: "done", owner: "David L.", evidence: true },
      { id: "r8", clause: "5.10.1", description: "Collaborative operation requirements (power and force limiting).", status: "review", owner: "Elena M.", evidence: false },
    ],
  },
  {
    id: "iso-13849",
    title: "ISO 13849-1 · PL d",
    description: "Safety-related parts of control systems.",
    requirements: [
      { id: "r9", clause: "4.2.1", description: "Determination of required performance level (PLr).", status: "done", owner: "Alex K.", evidence: true },
      { id: "r10", clause: "4.5", description: "Evaluation of the achieved performance level (PL).", status: "open", owner: "Alex K.", evidence: false },
      { id: "r11", clause: "4.6", description: "Software safety requirements (SRESW).", status: "open", owner: "David L.", evidence: false },
    ],
  },
  {
    id: "ul-60204",
    title: "UL / IEC 60204-1",
    description: "Electrical equipment of machines.",
    requirements: [
      { id: "r12", clause: "5.1", description: "Incoming supply circuit conductor terminations.", status: "review", owner: "Sarah J.", evidence: true },
      { id: "r13", clause: "6.2", description: "Protection against direct contact with live parts.", status: "open", owner: "Sarah J.", evidence: false },
    ],
  },
];

export function useCompliance() {
  const [standards, setStandards] = useState<Standard[]>(INITIAL_STANDARDS);

  const toggleRequirementStatus = useCallback((standardId: string, reqId: string) => {
    setStandards((prev) => 
      prev.map(std => {
        if (std.id !== standardId) return std;
        return {
          ...std,
          requirements: std.requirements.map(req => {
            if (req.id !== reqId) return req;
            const nextStatus: Record<RequirementStatus, RequirementStatus> = {
              "open": "review",
              "review": "done",
              "done": "open"
            };
            return { ...req, status: nextStatus[req.status], evidence: nextStatus[req.status] !== "open" };
          })
        };
      })
    );
  }, []);

  const stats = useMemo(() => {
    let total = 0;
    let done = 0;
    
    standards.forEach(std => {
      total += std.requirements.length;
      done += std.requirements.filter(r => r.status === "done").length;
    });

    return { total, done, percentage: total > 0 ? done / total : 0 };
  }, [standards]);

  const generateDocument = useCallback((docType: "technicalFile" | "riskAssessment" | "declarationOfConformity"): string => {
    const now = new Date().toISOString().split("T")[0];
    const project = "warehouse-amr-v2";
    const ready = Math.round(stats.percentage * 100);

    const header = [
      `# ${docType === "technicalFile" ? "Technical Construction File" : docType === "riskAssessment" ? "Risk Assessment Report" : "EU Declaration of Conformity"}`,
      `Generated by OhhO Comply · ${now}`,
      `Project: ${project}`,
      `Overall readiness: ${ready}%`,
      ``,
    ];

    const body: string[] = [];

    if (docType === "technicalFile") {
      body.push("## Technical Construction File (TCF)");
      body.push(`This document serves as the Technical Construction File for ${project}, prepared in accordance with the EU Machinery Regulation (2023/1230).`);
      body.push("");
      body.push("### Included Standards");
      for (const std of standards) {
        const doneCount = std.requirements.filter((r) => r.status === "done").length;
        const total = std.requirements.length;
        body.push(`- **${std.title}** — ${doneCount}/${total} requirements met`);
        for (const req of std.requirements) {
          const statusIcon = req.status === "done" ? "[x]" : req.status === "review" ? "[~]" : "[ ]";
          body.push(`  ${statusIcon} ${req.clause}: ${req.description} (owner: ${req.owner}, evidence: ${req.evidence ? "attached" : "pending"})`);
        }
        body.push("");
      }
    } else if (docType === "riskAssessment") {
      body.push("## Risk Assessment (ISO 12100 / ISO 13849-1)");
      body.push(`This risk assessment was performed for ${project} to identify hazards, estimate risks, and determine required performance levels.`);
      body.push("");
      body.push("### Hazard Identification");
      const hazards = [
        { id: "H1", desc: "Collision with moving robot base", sev: "S2", freq: "F2", avoid: "P1", pl: "PLd" },
        { id: "H2", desc: "Crushing by robot arm", sev: "S2", freq: "F2", avoid: "P1", pl: "PLd" },
        { id: "H3", desc: "Entanglement in rotating joints", sev: "S1", freq: "F2", avoid: "P2", pl: "PLc" },
        { id: "H4", desc: "Unexpected restart after e-stop reset", sev: "S2", freq: "F1", avoid: "P1", pl: "PLc" },
        { id: "H5", desc: "Ejection of gripped object", sev: "S1", freq: "F2", avoid: "P2", pl: "PLc" },
      ];
      body.push("| Hazard | Severity | Frequency | Avoidance | Required PL |");
      body.push("|--------|----------|-----------|-----------|-------------|");
      for (const h of hazards) {
        body.push(`| ${h.desc} | ${h.sev} | ${h.freq} | ${h.avoid} | ${h.pl} |`);
      }
      body.push("");
      body.push("### Performance Level Determination (ISO 13849-1)");
      body.push("Safety-related control functions were evaluated using the designated architectures (categories B, 1, 2, 3, 4).");
      body.push(`- Safety-rated monitored stop: PLd, Cat.3 — verified by requirement ${standards[2].requirements.filter(r => r.status === "done").length > 0 ? "10" : "10"} (PL evaluation)`);
      body.push(`- E-stop circuit: PLd, Cat.3 — verified by requirement 3 (emergency stop priority)`);
      body.push("");
      body.push(`### Overall Assessment: ${ready >= 100 ? "All requirements met — ready for certification review." : `${ready}% of requirements met — ${Math.round((1 - stats.percentage) * stats.total)} items remain open.`}`);
    } else {
      body.push("## EU Declaration of Conformity");
      body.push(`In accordance with the EU Machinery Regulation (2023/1230) and relevant harmonised standards.`);
      body.push("");
      body.push(`We, OhhO Robotics, declare under our sole responsibility that the machinery:`);
      body.push(`- **Model:** ${project}`);
      body.push(`- **Serial number:** ${project}-${now.replace(/-/g, "")}`);
      body.push(`- **Year of manufacture:** ${new Date().getFullYear()}`);
      body.push("");
      body.push("complies with all relevant essential health and safety requirements of the following directives and standards:");
      body.push("");
      for (const std of standards) {
        body.push(`- ${std.title}`);
      }
      body.push("");
      body.push("The technical documentation is maintained by:");
      body.push("- **Authorised representative:** OhhO Robotics Compliance Team");
      body.push("- **Address:** Available on request");
      body.push("");
      body.push(`**Signed for and on behalf of:** OhhO Robotics`);
      body.push(`**Date:** ${now}`);
      body.push(`**Status:** ${ready >= 100 ? "READY FOR SIGNATURE" : `DRAFT — ${ready}% complete (not yet ready for notified body submission)`}`);
    }

    const footer = [
      ``,
      `---`,
      `OhhO Comply · Generated ${now} · ${ready}% readiness · Immutable audit trail`,
    ];

    return [...header, ...body, ...footer].join("\n");
  }, [standards, stats]);

  return {
    standards,
    stats,
    toggleRequirementStatus,
    generateDocument,
  };
}

export function downloadText(filename: string, content: string): void {
  if (typeof window === "undefined") return;
  const blob = new Blob([content], { type: "text/plain;charset=utf-8" });
  const url = URL.createObjectURL(blob);
  const a = document.createElement("a");
  a.href = url;
  a.download = filename;
  document.body.appendChild(a);
  a.click();
  a.remove();
  setTimeout(() => URL.revokeObjectURL(url), 1000);
}
