/*
 * Copyright (c) Meta Platforms, Inc. and affiliates.
 * All rights reserved.
 *
 * Licensed under the Oculus SDK License Agreement (the "License");
 * you may not use the Oculus SDK except in compliance with the License,
 * which is provided at the time of installation or download, or which
 * otherwise accompanies this software in either electronic or hard copy form.
 *
 * You may obtain a copy of the License at
 *
 * https://developer.oculus.com/licenses/oculussdk/
 *
 * Unless required by applicable law or agreed to in writing, the Oculus SDK
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

using UnityEngine;
using UnityEngine.Animations;

namespace Oculus.Interaction.Samples
{
    /// <summary>
    /// The ISDK Scene Manager handles the enabling and disabling
    /// of the ISDK Menu panel and plays audio for each action.
    /// </summary>
    [RequireComponent(typeof(ParentConstraint))]
    public class ISDKSceneMenuManager : MonoBehaviour
    {
        /// <summary>
        /// The Parent Object of the Menu
        /// </summary>
        [Tooltip("The parent object of the menu")]
        [Header("Place the grabbable parent object here")]
        [SerializeField]
        private GameObject _menuParent;

        /// <summary>
        /// The audio to play when showing the menu panel
        /// </summary>
        [Tooltip("The audio to play when showing the menu panel")]
        [Header("Place the menu open audio here")]
        [SerializeField]
        private AudioSource _showMenuAudio;

        /// <summary>
        /// The audio to play when hiding the menu panel
        /// </summary>
        [Tooltip("The audio to play when hiding the menu panel")]
        [Header("Place the menu hide audio here")]
        [SerializeField]
        private AudioSource _hideMenuAudio;

        /// <summary>
        /// The location the menu should be spawning at
        /// </summary>
        [Tooltip("The location the menu should be spawning at")]
        [Header("The location the menu should be spawning at")]
        [SerializeField]
        private GameObject _spawnPoint;

        [Tooltip("The camera used to determine if the menu is in view")]
        [Header("The camera used to determine if the menu is in view")]
        [SerializeField, Optional(OptionalAttribute.Flag.AutoGenerated)]
        private Camera _viewCamera;

        protected bool _started = false;
        private ParentConstraint _parentConstraint;
        protected virtual void Start()
        {
            this.BeginStart(ref _started);
            this.AssertField(_menuParent, nameof(_menuParent));
            this.AssertField(this._showMenuAudio, nameof(_showMenuAudio));
            this.AssertField(this._hideMenuAudio, nameof(_hideMenuAudio));
            this.AssertField(this._spawnPoint, nameof(_spawnPoint));

            if (_viewCamera == null)
            {
                _viewCamera = Camera.main;
            }

            _parentConstraint = GetComponent<ParentConstraint>();
            ParentToOVRCameraRig();

            this.EndStart(ref _started);
        }

        private void ParentToOVRCameraRig()
        {
            var ovrCameraRig = FindAnyObjectByType<OVRCameraRig>();
            if (ovrCameraRig == null)
            {
                return;
            }

            var rigConstraintSource = new ConstraintSource();
            rigConstraintSource.sourceTransform = ovrCameraRig.transform;
            rigConstraintSource.weight = 1f;

            _parentConstraint.AddSource(rigConstraintSource);
            _parentConstraint.constraintActive = true;
        }

        /// <summary>
        /// Show/hide the menu.
        /// </summary>

        public void ToggleMenu()
        {
            bool menuIsActiveAndInView = _menuParent.activeSelf && IsMenuInView();

            if (menuIsActiveAndInView)
            {
                _hideMenuAudio.Play();
                _menuParent.SetActive(false);
            }
            else
            {
                _showMenuAudio.Play();
                _menuParent.transform.position = _spawnPoint.transform.position;
                _menuParent.transform.rotation = GetVerticalRotation(_spawnPoint.transform.rotation);
                _menuParent.SetActive(true);
            }
        }

        private bool IsMenuInView()
        {
            if (_viewCamera == null)
            {
                return true;
            }
            Vector3 directionToMenu = (_menuParent.transform.position - _viewCamera.transform.position).normalized;
            Vector3 cameraForward = _viewCamera.transform.forward;

            float dot = Vector3.Dot(cameraForward, directionToMenu);
            float halfFovRad = _viewCamera.fieldOfView * 0.5f * Mathf.Deg2Rad;
            float viewThreshold = Mathf.Cos(halfFovRad);

            return dot >= viewThreshold;
        }

        private Quaternion GetVerticalRotation(Quaternion rotation)
        {
            Vector3 euler = rotation.eulerAngles;
            return Quaternion.Euler(0f, euler.y, 0f);
        }

        #region Injects
        public void InjectAllMenuItems(GameObject parent,
            AudioSource show, AudioSource hide, GameObject spawnpoint)
        {
            InjectMenuParent(parent);
            InjectShowAudio(show);
            InjectHideAudio(hide);
            InjectSpawnPoint(spawnpoint);
        }

        public void InjectMenuParent(GameObject parent)
        {
            _menuParent = parent;
        }

        public void InjectShowAudio(AudioSource show)
        {
            _showMenuAudio = show;
        }

        public void InjectHideAudio(AudioSource hide)
        {
            _hideMenuAudio = hide;
        }

        public void InjectSpawnPoint(GameObject spawnpoint)
        {
            _spawnPoint = spawnpoint;
        }

        public void InjectOptionalViewCamera(Camera viewCamera)
        {
            _viewCamera = viewCamera;
        }
        #endregion
    }
}
